name: Deploy s3 bucket in aws
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK: aws_s3
jobs:
  setup-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pulumi pulumi_aws
      - name: Login to Pulumi
        run: |
          pulumi login  ${PULUMI_ACCESS_TOKEN}
      - name: Create Pulumi Stack
        run: |
          pulumi stack init ${PULUMI_STACK}
        continue-on-error: true
      - name: Select Pulumi Stack
        run: |
          pulumi stack select ${PULUMI_STACK}
      - name: Run a plan
        run: |
          pulumi preview
      - name: Destroy Pulumi Stack
        run: |
          pulumi up --yes
